import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

const font = Open_Sans({
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Concord",
  description: "Generated by create next app",
  icons: "/icon/concord-icon.svg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      theme : dark
    }}>
      <html lang="en">
        <body
          className={` ${font.className} antialiased`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
